### ISSUE TITLE
Contact us: Other info of the address should move up to fill the empty space.

### ISSUE THREAD

**Issue by Atcharanak** [titan-cebu/Boynes-Springs#50]
![image](https://cloud.githubusercontent.com/assets/11186313/14973746/382fcb1a-111e-11e6-9645-e84a16cad1bc.png)

**Comment by p-wanlaphakorn** [comment]
I fixed it.
if the address isn't complete it won't show at all because if it shows the uncompleted address, map is broken. The address one is related to the map.

**Comment by Atcharanak** [comment]
Issue still happen, i have tried to remove Suburb(in the backend) so frontend should not have the empty space. Could you please fix it?

![image](https://cloud.githubusercontent.com/assets/18587097/15347115/a6986e38-1ce8-11e6-9cbb-c35c2a0af1c6.png)


Also update the text "Address" to "Postal Address"

![image](https://cloud.githubusercontent.com/assets/18587097/15347195/6879bbd8-1ce9-11e6-8478-7c9664ddf4d1.png)
